apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubernetic.name" . }}-backend
  labels:
    app.kubernetes.io/component: backend
{{ include "kubernetic.labels" . | indent 4 }}
{{- with .Values.backend.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.backend.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: 1
  strategy:
{{ toYaml .Values.backend.updateStrategy | indent 4 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kubernetic.name" . }}-backend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
{{- with .Values.backend.podAnnotations }}
{{ toYaml . | indent 8 }}
{{- end }}
      labels:
        app.kubernetes.io/name: {{ include "kubernetic.name" . }}-backend
        app.kubernetes.io/instance: {{ .Release.Name }}
{{- with .Values.backend.podLabels }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
    {{- with .Values.backend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: kubernetic-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /go/config/config.yaml
            name: config
            subPath: config.yaml
          - name: preferences
            mountPath: /preferences
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "kubernetic.serviceAccountName" . }}
    {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: config
        secret:
          secretName: {{ include "kubernetic.fullname" . }}
      - name: preferences
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "kubernetic.fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
