{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubernetic.fullname" . }}:{{ .Release.Namespace }}
  labels:
{{ include "kubernetic.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ include "kubernetic.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
