apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetic.fullname" . }}
  labels:
{{ include "kubernetic.labels" . | indent 4 }}
type: Opaque
data:
  {{- /* Make a deep enough copy of the default config */}}
  {{- $c := dict }}
  {{- range $key, $dictVal := .Values.config }}
  {{- $dictCopy := merge (dict) $dictVal }}
  {{- $_ := set $c $key $dictCopy }}
  {{- end }}

  config.yaml: {{ $c | toYaml | b64enc }}