apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: kubernetic
version: 0.1.0
dependencies:
    - name: kubernetic-backend
      repository: file://../kubernetic-backend
      version: 0.1.0
    - name: kubernetic-frontend
      repository: file://../kubernetic-frontend
      version: 0.1.0
