apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubernetic.name" . }}-frontend
  labels:
    app.kubernetes.io/component: frontend
{{ include "kubernetic.labels" . | indent 4 }}
{{- with .Values.frontend.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.frontend.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kubernetic.name" . }}-frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
{{- with .Values.frontend.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
      labels:
        app.kubernetes.io/name: {{ include "kubernetic.name" . }}-frontend
        app.kubernetes.io/instance: {{ .Release.Name }}
{{- with .Values.frontend.podLabels }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
    {{- with .Values.frontend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: kubernetic-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          env:
          - name: PORT
            value: "80"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
