apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubernetic.name" . }}-frontend
  labels:
{{ include "kubernetic.labels" . | indent 4 }}
{{- with .Values.frontend.service.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.frontend.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "kubernetic.name" . }}-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
